version: '3.7'

services:
  download-template:
    image: alpine/git
    container_name: download-template
    command: ["-c", "cd /build/ && ls -la && git clone https://github.com/searx/searx-docker && mkdir -p filtron/ && mkdir -p caddy/ && mv ./searx-docker/Caddyfile /build/caddy/ && mv ./searx-docker/rules.json /build/filtron/ && ls -la /build/ && ls -la /build/caddy/ && ls -la /build/filtron/"]
    entrypoint: "ash"
    volumes:
      - caddy-routes:/build/caddy/:rw
      - filtron-config:/build/filtron/:rw
      - .:/git
      
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    depends_on:
      - "download-template"
    restart: on-failure
    ports:
      - ${CADDY_HTTP_PORT:-8088}:80
      - ${CADDY_HTTPS_PORT:-4443}:443
    networks:
      - searx
    volumes:
      - caddy-routes:/etc/caddy/:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARX_HOSTNAME=${SEARX_HOSTNAME:-localhost}
      - SEARX_TLS=${LETSENCRYPT_EMAIL:-internal}

  filtron:
    container_name: filtron
    image: dalf/filtron
    depends_on:
      - "download-template"
    restart: always
    ports:
      - "4040:4040"
      - "4041:4041"
    networks:
      - searx
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searx:8080
    volumes:
      - filtron-config:/etc/filtron/:rw
    read_only: true

  searx:
    container_name: searx
    image: searx/searx:latest
    depends_on:
      - "download-template"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - searx
    command: ${SEARX_COMMAND:-}
    volumes:
      - searx-data:/etc/searx:rw
      - searx-data:/var/log/uwsgi:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARX_HOSTNAME:-localhost}/
      - MORTY_URL=https://${SEARX_HOSTNAME:-localhost}/morty/
      - MORTY_KEY=${MORTY_KEY}

  morty:
    container_name: morty
    image: dalf/morty
    depends_on:
      - "download-template"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - searx
    command: -timeout 6 -ipv6
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS=0.0.0.0:3000
    read_only: true

networks:
  searx:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:
  caddy-routes:
  filtron-config:
  searx-data:
