version: '3.7'

services:
  download-template:
    image: alpine/git
    container_name: download-template
    command: sh -c "
        cd /build/ &&
        git clone https://github.com/searx/searx-docker &&
        mkdir filtron && mkdir caddy &&
        mv ./searx-docker/Caddyfile /build/caddy &&
        mv ./searx-docker/rules.json /build/filtron
      "
    volumes:
      - caddy-routes:/build/caddy
      - filtron-rules:/build/filtron
      
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    depends_on:
      - "download-template"
    restart: on-failure
    network_mode: host
    networks:
      - searx
    volumes:
      - caddy-routes:/etc/caddy:rw
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARX_HOSTNAME=${SEARX_HOSTNAME:-localhost}
      - SEARX_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE

  filtron:
    container_name: filtron
    image: dalf/filtron
    depends_on:
      - "download-template"
    restart: always
    ports:
      - "127.0.0.1:4040:4040"
      - "127.0.0.1:4041:4041"
    networks:
      - searx
    command: -listen 0.0.0.0:4040 -api 0.0.0.0:4041 -target searx:8080
    volumes:
      - filtron-rules:/etc/filtron/rules.json:rw
    read_only: true
    cap_drop:
      - ALL

  searx:
    container_name: searx
    image: searx/searx:latest
    depends_on:
      - "download-template"
    restart: always
    networks:
      - searx
    command: ${SEARX_COMMAND:-}
    volumes:
      - searx-config:/etc/searx:rw
    environment:
      - BIND_ADDRESS=0.0.0.0:8080
      - BASE_URL=https://${SEARX_HOSTNAME:-localhost}/
      - MORTY_URL=https://${SEARX_HOSTNAME:-localhost}/morty/
      - MORTY_KEY=${MORTY_KEY}
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  morty:
    container_name: morty
    image: dalf/morty
    depends_on:
      - "download-template"
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - searx
    command: -timeout 6 -ipv6
    environment:
      - MORTY_KEY=${MORTY_KEY}
      - MORTY_ADDRESS=0.0.0.0:3000
    logging:
      driver: none
    read_only: true
    cap_drop:
      - ALL

networks:
  searx:
    ipam:
      driver: default

volumes:
  caddy-data:
  caddy-config:
  caddy-routes:
  filtron-rules:
  searx-config:
